# Generated by Django 2.2.3 on 2019-09-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_image', models.CharField(max_length=100)),
                ('processed_image_0', models.CharField(blank=True, max_length=100)),
                ('processed_image_1', models.CharField(blank=True, max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(max_length=10)),
            ],
        ),
    ]
