# Generated by Django 2.2.3 on 2019-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
