# Generated by Django 2.2.3 on 2019-09-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_type',
        ),
    ]
