# Generated by Django 2.2.3 on 2019-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_operation_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='processed_image_0',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='processed_image_1',
        ),
        migrations.AddField(
            model_name='operation',
            name='raw_image_name',
            field=models.CharField(default='image.jpg', max_length=128),
        ),
        migrations.AlterField(
            model_name='operation',
            name='raw_image',
            field=models.CharField(max_length=128),
        ),
    ]
