# Generated by Django 2.2.3 on 2019-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190903_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='processed_image_0',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='operation',
            name='processed_image_1',
            field=models.CharField(default='', max_length=128),
        ),
    ]
