# Generated by Django 2.2.3 on 2019-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20190905_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='processed_image_crop',
            field=models.CharField(default='', max_length=128),
        ),
    ]
